### ISSUE TITLE
Plasma lamps too dim

### ISSUE THREAD

**Issue by Zygus42** [mcenderdragon/Futurepack-API#109]
You have these giant bases with plasma lamps in the ceiling, but then you have to put torches on the floor to light them up enough to stop spawning.  Other than as decoration, no one is ever going to spend resources building a plasma lamp, when they could use a torch, glowstone, redstone lamp or lit pumpkin to provide more light cheaper.  Is this an intentional design ?

**Comment by ghost** [comment]
Lamps have sufficient light level, issue is in construction of the dungeon - replace the lamp with torch and you will see same light level. Also lamps are needed since torches aren't capable of lighting top of your ship.

P.S. personally I would have loved to have pillar and half-slab variations of the lamp and may be something wall mounted (sided slab?). Current variation looks good only in walls/floors/ceilings, not on them.

**Comment by mcenderdragon** [comment]
I will close this:
- texture of plasma lamp has chnaged
- generation of dungeon has changed

If this is still a problem please reopen the issue or create a new one.
