### ISSUE TITLE
Oredict compatibility for Researcher

### ISSUE THREAD

**Issue by Divineaspect** [mcenderdragon/Futurepack-API#114]
For example the researcher doesn't accept  Immersive Engineering Bauxite (which is what we unified our oregen around), because the input isn't oredicted.

**Comment by mcenderdragon** [comment]
the researcher is oredict compatible (tested woth our own server with copper from different mods). As far as I know we did not register our bauxit to avoid unbalancing IC². But I dont know exactly.

**Comment by Wugand** [comment]
We use "oreBauxite" and Immersive Engineering "oreAluminum". We think Bauxite is the more correctly solution. Specially because we don't like to have direkt smelt recipies.

In terms of your problem, we added "oreAluminum" as an alternative for the Research. But note that this don't make the ores compatible*, you only get the chanche to unlock all content, without having Bauxite from our mod. (in other words you don't need our ore)

*If you necessarily need full compatibility, try to ask Immersive Engineering to change/add the OreDict name ("oreBauxite").
