### ISSUE TITLE
Result of traveling to Menelaus

### ISSUE THREAD

**Issue by kremnev8** [mcenderdragon/Futurepack-API#125]
After traveling to Menelaus my ship was completely unusable. I know that it's not your fault that blocks lost their settings. But your mod also forgot to get some blocks of my ship and left them in overworld. In particular some parts of glass windows in floor and ceiling, ProjectRed wires, Microblocks, some EnderIO energy conduits, Tesseract(EnderIO analog), EnderIO Storage blocks, vanila Quartz stairs, vanila lever and vanila workbench. 
![2017-02-22_16 47 57_2](https://cloud.githubusercontent.com/assets/12484618/23216197/27fa85e6-f926-11e6-9cde-dfce0dd94723.png)

**Comment by mcenderdragon** [comment]
Have you a picture of the Spceship before the jump ? I am asking because online blocks surrounded by metal blocks will be transported and glass blocks from other mods are mostlikely not metal but insrtead glass. Also maybe you can provide also the complete world with ship

**Comment by kremnev8** [comment]
I can give you a map, but my modpack has a lot of mods(80)
Here is screenshots:
![2017-02-22_15 12 10](https://cloud.githubusercontent.com/assets/12484618/23223336/dbd57818-f93b-11e6-8009-8f3cb4e64c70.png)
![2017-02-22_15 11 15](https://cloud.githubusercontent.com/assets/12484618/23223332/dbc9e5a2-f93b-11e6-9e1b-a85061f5113a.png)
![2017-02-22_15 11 19](https://cloud.githubusercontent.com/assets/12484618/23223337/dbe141a2-f93b-11e6-8a2c-fc2038d8bd86.png)
![2017-02-22_15 11 36](https://cloud.githubusercontent.com/assets/12484618/23223335/dbcae506-f93b-11e6-92ef-eae66ca6e02d.png)
![2017-02-22_15 11 48](https://cloud.githubusercontent.com/assets/12484618/23223333/dbc9fc9a-f93b-11e6-9188-aa55718faa7b.png)
![2017-02-22_15 11 56](https://cloud.githubusercontent.com/assets/12484618/23223334/dbca60d6-f93b-11e6-8fc9-afbaf3c06e7a.png)
![2017-02-22_15 12 05](https://cloud.githubusercontent.com/assets/12484618/23223339/dc127db2-f93b-11e6-943b-0a2ea84be7a5.png)

**Comment by mcenderdragon** [comment]
Yeah the vanilla workbench in the button is not out of metal, so it wont be ported. All the Blue lights are outside of the ship and propably not metal (as thy were not ported). The glass is propably material glass and not metal, ours are metal. And the stairs and half steps are probabpy not metal too. You can try to build over and under each block that was not ported a metal block, but that probably wont look very well. 

After the jump back was your spaceship correct in one part ?

**Comment by kremnev8** [comment]
After jump i just restored all blocks by hand and destroyed them in overworld. But i can jump back to Menelaus to check that.
I think that even though they not metal, they part of the ship and most of them had at least 1 side connected to Metal blocks(Except glass). What about glass your glass won't connect textures to each other, so i choose TC glass.

**Comment by kremnev8** [comment]
And also you have small bug with upside down stairs:
![2017-02-22_20 51 04](https://cloud.githubusercontent.com/assets/12484618/23224863/f763e8e4-f940-11e6-936d-97f4ceaa298b.png)
That's why i use there Quartz stair

**Comment by Wugand** [comment]
Here a quote from your ingame description Texts:
"I can build my spaceship in any shape and size I want, but it is important that it have a solid metal block cover, as it is this cover that transports its metal framework and all the blocks, players, and creatures that are within it."

In other words, you have to make the hull completly out of metal blocks. (Since last Version you can scan Blocks with the E-Scanner to see, if they are valid for the surface.) Your lights, glass and coverd redstone are unforunaly not valid, so you should only them inside your ship. But not on the surface.

**Comment by kremnev8** [comment]
Okay, but what about workbench. underneath it there is a metal block and 3 sides except TechTable also Metal Blocks. Why it was not transported? Only because not metal?

**Comment by Wugand** [comment]
No inside the ship is everthing ok ... it looks like that it stand under the glass roof. And so it is maybe  selected as "outside". With the TC glass the alogithm wasn't able to get the shape of the spaceship.

For you case you have to replace it with our (or other valid) glass and look that at least one layer of metal blocks covers the Redstone-Parts. 
*Dirty trick: use a wire or pipe as wall and cover it with everything you want (Hologram Editor)

Sorry that we have no Fix/universal solution for you.

**Comment by Cat09** [comment]
this problem could be helped some perhaps by the use of an item that sets an additional block property (functioning in practice somewhat like thaumcraft's warding). For implementation, it might have to be different in order to be usable on tile entities. Perhaps a system with a block on the ship that you link to a tool that is used on any items you desire to act as "hull" items would work? Anything that allows you to remember a relative location rather than adding to block/world data should be a relatively sturdy system.

**Comment by mcenderdragon** [comment]
Well we could add a thin metal block wich is only visible if you held the holoramm editor or something like this.

**Comment by kleshchevand** [comment]
There might be other solutions to that. redpower mod used special covers to let attached 'outside' blocks to be transported. EnderIo has a facade block that can assume any texture. Also some kind of "damage computer"/"Room controller"/"Pressure checker" can be used to notify player if room is not sealed (because dragging computer to each room or having one in each isn't fun). Can be especially important for players that use automated doors (like pistons) and forgot to close their room before leaving to next planet (in such case such controller can even emit sinal before jump to close doors or shut down everything).

**Comment by mcenderdragon** [comment]
we have our pipes/wires wich can also be displayed as any block -> hologram editor. And if the doors are open closes only affect if you can jump or not, it doesnt effect what gets tranported or not. As long as you have a stable metal hull everything is fine.
