### ISSUE TITLE
[Suggestion for future] fix/enhance current jei support

### ISSUE THREAD

**Issue by meelock** [mcenderdragon/Futurepack-API#132]
My personal thought is that the current jei support is both ugly, (doesn't fit the theme of futurepack) and kinda buggy. My suggestion is that the jei recipes are made sure to only appear in jei when they have been researched, because having all the recipes you can't craft, I feel, just bloats the recipe viewer so that you can't find the item that you are looking for.

I hope you guys consider this!

thanks

**Comment by meelock** [comment]
ps. conversation is highly encouraged!

**Comment by mcenderdragon** [comment]
well I spoke with mezz about this and its not realy possible to hide the recipes. because for performance reasons every recipe is stored in a fast map, but as you find a new recipe things have to get updated and adding recipes is possible but removing them not realy. Also not showing the recipes sometimes result in players to think this is not posible to reach, so we decided to make it with this symbol but changing this is possible if every sides agree.

**Comment by meelock** [comment]
I would say that this is good enough to close this issue, but I hope that one day, better jei support would be quite nice, even if it is just a retexture.

thanks!``
