### ISSUE TITLE
[1.11.2][25.2.8] Question -- Signal Logistics

### ISSUE THREAD

**Issue by savosdarkran** [mcenderdragon/Futurepack-API#167]
Does network cable transmit all types of signals?  ( support, energy, items )?

Transmitters I assume by the description receive and transmit.  I had them in a line, see images.

![2017-05-01_13 58 56](https://cloud.githubusercontent.com/assets/26523998/25588497/84e0779a-2e76-11e7-9d7f-9d839b5dcf10.png)
![2017-05-01_13 58 02](https://cloud.githubusercontent.com/assets/26523998/25588506/8884962e-2e76-11e7-9830-c17eaba29bbb.png)
![2017-05-01_13 59 03](https://cloud.githubusercontent.com/assets/26523998/25588508/8a5c2e6c-2e76-11e7-8943-f4a161322042.png)
![2017-05-01_14 01 12](https://cloud.githubusercontent.com/assets/26523998/25588534/aad8346a-2e76-11e7-81d3-5230a94a7000.png)

I don't get power on the other side.  Do you need to sync them?

**Comment by mcenderdragon** [comment]
You have understood the conecüt wrong, the network part is synconized, not the energy part, if you put a T1 modul there then the Forsche will also draw nergy from this T1 modul. The lasers and also antennas extend the network.

**Comment by savosdarkran** [comment]
So all but energy go over the laser transmitters?  Is there anything to extend power?

**Comment by mcenderdragon** [comment]
wires and neon pipes. or a autom,ated system to charge and uncharteg batterys and sending them. But wires are not so pricy.

**Comment by savosdarkran** [comment]
ooo... Light bulb :D

Thanks so much for being patient with me while I learn this mod.  I'm having a blast.

**Comment by mcenderdragon** [comment]
💡

**Comment by savosdarkran** [comment]
So I want to be perfectly clear about the transmission system.  Please see the chart I made.  What's wrong, right, or missing?:)

![image](https://cloud.githubusercontent.com/assets/26523998/25589588/2a833d14-2e7b-11e7-8800-82d989500453.png)

**Comment by mcenderdragon** [comment]
redstoen pipe can transfer items as well, neon pipe can tranfer items as well. normal cable ponly neon, redstotne cable neon and redstone, support cable nneon + support, network cable neon  + network, no support no items.

**Comment by savosdarkran** [comment]
okay.  I have some more exploration to do :)

Cheers.

**Comment by savosdarkran** [comment]
![image](https://cloud.githubusercontent.com/assets/26523998/25589937/745dcbb0-2e7c-11e7-8c76-59e513a403f7.png)

**Comment by mcenderdragon** [comment]
* Fluid Tubes. They will be completly independent.

**Comment by savosdarkran** [comment]
gotcha.

Thanks again I really really really really appreciate it.

**Comment by Wugand** [comment]
Do you read the in-game "documentation" (the text in the research nodes for the pipes/cables) ?
If yes, are they so hard to understand ?

I only ask to knew, if they should be improved.

**Comment by savosdarkran** [comment]
I wasn't clear on the definition of "network".  I was under the impression that it would carry all types.  Not just network and neon.  As I understand now network is a separate type.  In the definition of network is says that modules do not have to be in the same location.  If a network cable does not support "support points" to be transferred then a support module would need to be directly beside the researcher.  Or is it just a matter of me unlocking the support cable?  I suppose things could be re-written to be clearer and a small chart unlocked at a certain point.

**Comment by kleshchevand** [comment]
Description is clear enough (except network cable, but it is covered in networks), but naming is a bit off... as well as combinations.
Redstone and network cable or support and network cables are very easy to confuse one with another if you don't read descriptions. And even then sometimes you wonder, what this Network cable is for. The problem lies in the fact that all three can be recognized as 'data' cables. I think these cables need tooltips which say what this cables are for at least and to be renamed at most (Control, Support and Link/Sync?)

P.S. Network cables don't seem to be that usefull, more decorative. So far I researched everything up to quantum (no idea what to scan to get past it, quantium ingot isn't researchable) with a single researcher and one module of each type.
Also for signal system to be complete machines need to be able to send redstone signals of their own - batteries/flashdrives/fuel tanks when full/empty, drone stations when no work/charge, neon furnance - when support full, centrifuge and opti-bench when no valid receipt (like one piece of cobble and can't continue) e t c

**Comment by mcenderdragon** [comment]
@kleshchevand thanks for the feedback this are very good ideas!

**Comment by mcenderdragon** [comment]
The wires have now new textures.
