### ISSUE TITLE
2nd planet, tyros?

### ISSUE THREAD

**Issue by LocoMinerDad** [mcenderdragon/Futurepack-API#199]
Is the planrt ready? I know you guys update stuff and somethings like the water coolibg arent 100%. Just want to know before i maje the 12 ftl etc. Thx

**Comment by mcenderdragon** [comment]
yeah you can reach tyros in 1.11 100% and in 1.10 I dont know exactly but i think there too.

**Comment by LocoMinerDad** [comment]
Ok thank you. Btw xan you guys add villages to your planets. Maybe more non vanilla stuff. The new cow and spiders were cool

**Comment by donqixot** [comment]
I tried to get to Tyros in 1.10.2 using 2 latest versions (24.2.144 and 24.2.145) and I am getting big question mark in advanced board computer. I took coordinates using telescope on Menelaus and I can see in NBTEditor these coordinates are for Tyros indeed, but ship computer does not get them. I tried both from Earth and from Menelaus. Dimension itself is fine, I can get there using another mod - Simple Dimensions, I can see Purple trees, glowmelons falling down, all good, but I cannot get there using spaceship. See attached picture from ship computer.
![image](https://cloud.githubusercontent.com/assets/12219588/26765853/a7893bbe-4952-11e7-9c94-4260762f7777.png)

**Comment by mcenderdragon** [comment]
This looks like you have not installed an FTL in your ship...

**Comment by donqixot** [comment]
Thanks, that was it, works perfect!

**Comment by ghost** [comment]
>This looks like you have not installed an FTL in your ship...

Made similar mistake at first - I did add FTL, but only one block, didn't expect it to be a multiblock so never read the whole 'research'.
Some kind of boardcomputer warning or status string is needed.

P.S. Are there any plans to add more dimentions to explore? I expected it to work more like mystcraft with ships instead of books plus some space objects to explore, yet there are only two planets which don't promote desire to explore space by much and no actuall access to said 'space'.

**Comment by mcenderdragon** [comment]
yeah a 3rd planet is planned, and dimension spamming like mystcraft is doing it is, well... alot of story is planed for the planets.

**Comment by ghost** [comment]
Thanks for the info.

FTL multiblock is described as 'unsafe for decoration' , why not take a page from Immersive engineering and use scrench (or other FP tool) to 'make' FTL?

Is there a way to add/register dimensions to FP? There are dimension mods, like Advanced Rocketry that add planets and it is weird to be able to travel to far off worlds and not be able to travel to closest ones, like AR-moon. Would have been perfect to be able to get to roofless world, use telescope to get current coordinates and later use those coordinates to move your ship...

**Comment by mcenderdragon** [comment]
@kleshchevand , yes there are ways to register dimensions. [registerMethod](https://github.com/mcenderdragon/Futurepack-API/blob/master/futurepack/api/FPApiMain.java#L41-L51) and [IPanet](https://github.com/mcenderdragon/Futurepack-API/blob/master/futurepack/api/interfaces/IPlanet.java)

Well multiblocks are a pain in the ass, so I am currently very happy they work (even if they are buggy as hell) Even if I use the scrench, breaking them is most likely problematic. But well I will dig into this and try to make it - lets say different, because I dont wont to promise to much ;)
