### ISSUE TITLE
[1.12] Dungeon Protection is causing severe lag spikes on server

### ISSUE THREAD

**Issue by DaedalusGame** [mcenderdragon/Futurepack-API#268]
Right after one of the players on our server found a huge future pack dungeon, lagspikes started happening. They got worse when other players explored more and found several others. I ran profiling on the server and found that it was using up a large chunk of cpu time in FPDungeonProtection onWorldSave.

[small screenshot of profiler output, probably doesn't have that much data for you](https://cdn.discordapp.com/attachments/335186981640339456/366007260645818378/unknown.png)

Removing FuturePack from the server fixed all lag spikes.

**Comment by mcenderdragon** [comment]
Does [this version](http://redsnake-games.de/Downloads/fp/fp.php?version=26.2.19) fixes this bug ?

**Comment by b0bst3r** [comment]
Lag spikes are being caused by FPDungeons.dat, ours is 2MB in size, if you remove it the lag spike is gone, put it back and the lag spike is back.  So the question is, what's in it and can it be removed?

**Comment by mcenderdragon** [comment]
while generating I have to save some data into chunks, but often enough I have the data before forge fires the events to save the chunk, to prevent data loose I write these data into an extra (already compressed) file "FPDungeons.dat". In the version above I moved everything interacting with this file into an extra thread so I doesnt impact performance anymore.

If you delete this file it can happen the dungeon protectiopn gets corrupted, so some part is not protected, and some is, but after finsihing the dungeons it can happen the dungeon core, can not shutdown dungeon protection completly.

@b0bst3r can you ran profiling and send me the results?

**Comment by b0bst3r** [comment]
I took the mod file you listed above and tried that and so far it seems to have fixed the issue.  Will keep you posted when more come online, but it's great so far.

**Comment by asim0v** [comment]
Any ETA on putting the fixed version on CurseForge? I have Futurapack in the custom mod pack for the server I administer. After a lengthy investigation, I determined that Futurepack was the cause of the 3 second lag spikes ever 45 seconds we are experiencing.

That investigation led me here, and I have confirmed that the version you linked to in this report fixes the lag issue on the server. But I cannot update the pack and server because the version is not on CurseForge and will get rejected.

Please get the updated version on CurseForge soon! Thanks!

**Comment by mcenderdragon** [comment]
@asim0v yes after #267 and #265 are fixed ;)
