### ISSUE TITLE
[Menelaus] Worldgen Lag Error

### ISSUE THREAD

**Issue by gwydion0917** [mcenderdragon/Futurepack-API#327]
My server is getting this error especially when going off world.

Futurepack loaded a new chunk (40, -34  Dimension: 73) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

**Comment by mcenderdragon** [comment]
yeah forge dont likes the menelaus worldgen. I dont know yet what part of the world gen is causing this.

**Comment by mandonnaud** [comment]
Hello,

The problem is always there?

[09:38:34] [Server thread/WARN]: Futurepack loaded a new chunk (-116, -377  Dimension: 73) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

Forge : 14.23.2.2616
FuturePack : 26.3.123 (last)
Solo game

I keep checking if I find a mod conflict
