### ISSUE TITLE
[Question] Red Laser Lens

### ISSUE THREAD

**Issue by DigitalSketch** [mcenderdragon/Futurepack-API#395]
How do I unlock the red laser lens?  I have 2 blueprints that require it, but I can't find where to unlock the red laser lens.

**Comment by mcenderdragon** [comment]
research the neon industrial furnace.

**Comment by DigitalSketch** [comment]
Thanks I got it, but trying to research the Network Transmitter, it won't take the network cables (we've already gotten that bug reported).  I can't figure out which command to throw to unlock it for me though.

**Comment by mcenderdragon** [comment]
this should be fixed.

**Comment by TheRealNinjaTTV** [comment]
Sorry to necro this topic but I have researched every aspect of the industrial neon furnace and cant get the Red Laser Lens BP out.

**Comment by mcenderdragon** [comment]
> Sorry to necro this topic but I have researched every aspect of the industrial neon furnace and cant get the Red Laser Lens BP out.

what version are you on ? have you right clicked the research?

**Comment by TheRealNinjaTTV** [comment]
1.16.5, can't right click anything

**Comment by mcenderdragon** [comment]
if you arent playing a modpack (which could have changed the recipes) then it definetly works as others have completed it. I think you need to be on menelaus firs tin order to get that. if you out the noen ind firnac ein the scanner have you reached verything or is a questoin mark displayed ?

**Comment by TheRealNinjaTTV** [comment]
With the Industrial Neon Furnace in the Scanner, I have 4 bars remaining on the left and a big yellow question mark when I scan. What is the Research Blueprint name for the Red Focus Lens? Sent from Mail for Windows From: mcenderdragonSent: Monday, May 2, 2022 8:03 AMTo: mcenderdragon/Futurepack-APICc: FraserTheNerd; CommentSubject: Re: [mcenderdragon/Futurepack-API] [Question] Red Laser Lens (#395) if you arent playing a modpack (which could have changed the recipes) then it definetly works as others have completed it. I think you need to be on menelaus firs tin order to get that. if you out the noen ind firnac ein the scanner have you reached verything or is a questoin mark displayed ?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by mcenderdragon** [comment]
> With the Industrial Neon Furnace in the Scanner, I have 4 bars remaining on the left and a big yellow question mark when I scan. What is the Research Blueprint name for the Red Focus Lens? Sent from Mail for Windows From: mcenderdragonSent: Monday, May 2, 2022 8:03 AMTo: mcenderdragon/Futurepack-APICc: FraserTheNerd; CommentSubject: Re: [mcenderdragon/Futurepack-API] [Question] Red Laser Lens (#395) if you arent playing a modpack (which could have changed the recipes) then it definetly works as others have completed it. I think you need to be on menelaus firs tin order to get that. if you out the noen ind firnac ein the scanner have you reached verything or is a questoin mark displayed ?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

use F3+H and yes this means you need to research at other stuff first to get the red lense.
