### ISSUE TITLE
Pusher can cause item duplication.

### ISSUE THREAD

**Issue by mcenderdragon** [mcenderdragon/Futurepack-API#450]
@TheRealM18 can you provide a descripton/video.

**Comment by TheRealM18** [comment]
I will make a video tomorrow on me doing it so that you will be able to see what is going on.  You need a scrench, a pusher, and a pickaxe.  The reason you need all three is that it is a combination of making it happen twice, though I found it on your favourite type of server ;) (Sponge) so it might be a bug in sponge.

**Comment by mcenderdragon** [comment]
Solved: [26.3.212](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.212)
