### ISSUE TITLE
Cap ladders

### ISSUE THREAD

**Issue by Divineaspect** [mcenderdragon/Futurepack-API#71]
Can a cap or locked door be added to the ladders?
We'd like to delay access to those chambers for narrative reasons.

**Comment by Divineaspect** [comment]
This would encourage people to not just strip the bases for their components in early game, where it's kinda a gamebreaker. But if they wan't to dig around to get in, that'd be possible.

**Comment by jelaw21** [comment]
I would like to vote for this. Or an option to lessen the numbers of those dens created, even take them out altogether. I found a left over space ship that was at least 6 chunks big and had most all of the items I could ever need.

**Comment by mcenderdragon** [comment]
Of wich dungeon are we talking about? @Divineaspect taljked about ladders, but only in the small one are ladders. @jelaw21 is talking about 6 chunk huge wrecked spacship, so he must mena the big ones. To lock the small ones whould be kind of impossible because they are the game start. Only there you can get the E-Scanner and start researching.
But locking the Big ones whould be possible, but what whould unlock they ?

**Comment by Divineaspect** [comment]
Some of this is probably in response to #72. But the dungeons  are so frequent and large that they commonly overlap.

**Comment by Divineaspect** [comment]
I  would suggest that they unlock with a diamond pick to break the block, or with an escanner acting as a key.

**Comment by mcenderdragon** [comment]
Also in the future dungeons have a protection so we can add locked rooms, boss chambers and stuff like that.
