### ISSUE TITLE
[1.16.4] FTL blocks don't drop when broken

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#737]
Forge version: 35.1.28
Futurepack version: 21.0.4

FTL Blocks don't drop when broken with a Composite Pickaxe.

I'm pretty sure they dropped when broken in an earlier version, so I'm reporting this as a bug.

![FTL_break](https://user-images.githubusercontent.com/32312262/103615199-71b77000-4f2a-11eb-9f42-29faa39054a0.gif)

**Comment by Wugand** [comment]
The loottable field in Block.Properties can be changed by .noDrops() permanently.
This is done in BlockHoldingTile Contructor, which removes loot from all later uses of the Block.Properties object.
*The fix is not universial since the line "super(hasNBTCustomDrops ? builder.noDrops() : builder);" from BlockHoldingTile is still able to corrupt Properties and assumes loot in passed Property is allways active.

@mcenderdragon you should find a solution for this
