### ISSUE TITLE
21.0.3 Rsearcher does not finish blueprints when two item stacks are required

### ISSUE THREAD

**Issue by 7eggert** [mcenderdragon/Futurepack-API#744]
Futurepack-1.16.4-21.0.3.jar
Minecraft/ forge-1.16.4-35.1.4.jar

Researcher is placed standalone. I put in the redstone cable blueprint.
When I only put in 8 Redstone, the white bar increases while the blue bar stays at 100%. Putting in the cable(s) does not change things.

**Comment by 7eggert** [comment]
Now I've placed it at a different location; I don't know what I did differently, but now it works.

**Comment by Yirok42** [comment]
The progress bars are not reliable. When in doubt, scan the researcher with the e-scanner and examine the attribute values. They come in pairs: neon, sneon, support, ssupport, ... I have had trouble in the past because more support was needed than was available, and instead of indicating partial completion, the progress bar shows 100%. Adding support to my support module, allowed progress to be made, and the progress bar to reflect the uncompleted status.

I am not saying this was your issue.
