### ISSUE TITLE
"Iron ladder" stop work as ladder

### ISSUE THREAD

**Issue by Apollon-Theos** [mcenderdragon/Futurepack-API#775]
Once "iron ladder" is no ladder. I remove all mods, that I add after begin play with FuturePack.
Iron Ladder can mine from tunnels to hidden room (3 death for test new situation - very high fall) and placed to wall, but not work.

**To Reproduce**
I unknown what need to reproduce.

**Additional context**

**Logs**
https://pastebin.com/Nx9N7rHH

**Comment by Apollon-Theos** [comment]
With Forge 36.0.36 "iron ladder" work
With Forge 36.0.55 not work
With Forge 36.1.0 not work
-> Set of mod not does not affect it.

**Comment by mcenderdragon** [comment]
I do not quite understand your problem. when I tested you can walk the iron ladder up  & down just fine...

**Comment by mcenderdragon** [comment]
also can you test with forge  1.16.5-36.0.44 and  1.16.5-36.0.45 ?

**Comment by meyron** [comment]
1.16.5-36.0.48 With mods seems not to be working. Tested on fresh world in single player also

**Comment by Apollon-Theos** [comment]
With Forge 36.0.44 - iron ladder work
With Forge 36.0.45 - not work.
Set of mods same as above.
Before logo of FuturePack short show "dirt" screen with 3 buttons, but very short.

44/45 I switch two time, result same.

**Comment by Wugand** [comment]
We proven that it is caused (in our case) by an incompatibility with Immersive Engineering (maybe also other, but this mod is reliable to reproduce). 

*This is not an accusation against Immersive Engineering or Futurepack, by now it is just the minimal subset of mods (Futurepack + Immersive Engineering) to reproduce the bug.

I currently not dived into the code, since I can't get Immersive running in Dev Env (because they using mixin).

**Comment by Apollon-Theos** [comment]
> *This is not an accusation against Immersive Engineering or Futurepack, by now it is just the minimal subset of mods (Futurepack + Immersive Engineering) to reproduce the bug.

No "Immersive Engineering" in mods. See my previous message, set of mods not changed, changed only version of Forge.
Before write issue, I change version of Forge to 36.0.44, because "Aquaculture" need version above 36.0.43.
All is work.
Next day I change version of Forge to 36.0.55 and has 3 death by visit to "hidden room". Iron ladder not work and entry to room as "very high fall".

Aquaculture-1.16.5-2.1.16.jar
ChickenDropFeathers-1.0-forge-1.16.5-36.0.0.jar

My set of mods (no other mod have "Iron Ladder"):
durability101-1.16-0.0.3.jar
Futurepack-1.16.4-31.1.8176.jar
jei-1.16.4-7.6.1.72.jar
JustEnoughResources-1.16.3-0.12.0.100.jar
mcw-furniture-2.0.1-mc1.16.5.jar
obfuscate-0.6.0-1.16.3.jar
productivebees-1.16.5-0.6.9.5.jar
repurposed_structures-1.16.5-2.5.0.jar
sleeping_bags-1.16.5-1.0.2.jar
Space-Bosstools-1.16.4-4.6.jar
tl_skin_cape_forge_1.16.5-1.17.jar
vanillacookbook-1.16.3-1.11.jar
Waystones_1_16_4.jar
XaerosWorldMap_1.12.2_Forge_1.16.5.jar
Xaeros_Minimap_21.4.2_Forge_1.16.5.jar
[1.16.5]+RecipeEnhancements-1.5.2.jar

**Comment by Wugand** [comment]
I was not intended to contradict you. 
Was just trying to get this happen by our self.

Update: The tester I instructed messed around with his Forge versions and ignored my "Change absolutly nothing else, but what i'am telling you". So my last finding are literally garbage. Only Futurepack and Forge 36.0.45 or above are needed. 

(Note by the way) Reason for my affort is to get a small setup where I can test my changes, since it's very hard to work on an bug you can't reproduce by your own or only in an larger modpack.

I now give the recomendations from the Forge issue a try.

**Comment by Yirok42** [comment]
@Wugand or @mcenderdragon, solved a month ago in dev. Is it available?

**Comment by mcenderdragon** [comment]
its released on curseforge
