### ISSUE TITLE
Experimental settings


### ISSUE THREAD

**Issue by Ashwinaaaaaaahdt** [mcenderdragon/Futurepack-API#982]
1.13-1.18.2
Please remove experimental settings as they are incompatible to some mods and make the config files of mods fail and don't work especially when the world is optimized and mod pack will fail

**Comment by mcenderdragon** [comment]
NO I will not remove all the worldgen of the mod, which is like the main feature. Please educate yourself before asking ridiculous things. All worldgen is now done via this system and is flagged as experimental settings, even if its fully done via code.

**Comment by Ashwinaaaaaaahdt** [comment]
> NO I will not remove all the worldgen of the mod, which is like the main feature. Please educate yourself before asking ridiculous things. All worldgen is now done via this system and is flagged as experimental settings, even if its fully done via code.

OK, sorry for that question, but what about updating futurepack from 1.19x to 1.20x? You haven't updated after May 28, 2023

**Comment by mcenderdragon** [comment]
Q: do you plan to update past 1.18 at some point in the future?
A: If there is at one point a real modding API that is stable for some versions and has not huge breaking changes every half year when a new minecraft version comes around then yes I will port the mod to that. But as we all know this will never be the case and I also didn't update the current 1.18 version because I simply lack the time so big updates are very unlikely. But other people can feel free to provide Merge Requests and update it bit by bit. gitlab & github was meant for that.

**Comment by Ashwinaaaaaaahdt** [comment]
> Q: do you plan to update past 1.18 at some point in the future?
> A: If there is at one point a real modding API that is stable for some versions and has not huge breaking changes every half year when a new minecraft version comes around then yes I will port the mod to that. But as we all know this will never be the case and I also didn't update the current 1.18 version because I simply lack the time so big updates are very unlikely. But other people can feel free to provide Merge Requests and update it bit by bit. gitlab & github was meant for that. 

Can you add a feature about the Redstone signaller that will release the Redstone signal when the Redstone controller is right-clicked, especially useful when TNT is stacked
